### PR TITLE
Add CraftTweaker support

### PR DESCRIPTION
**Pull request by eutro**
This PR adds CraftTweaker support for the cooking pot and the cutting board.
The `farmersdelight:cooking` recipe manager has a new method:
```zs
// <recipetype:farmersdelight:cooking>.addRecipe(String name, IItemStack output, IIngredient[] inputs, @Optional IItemStack container, @OptionalFloat float experience, @OptionalInt(200) int cookTime)

<recipetype:farmersdelight:cooking>.addRecipe("test_cooking", <item:minecraft:diamond>, [<item:minecraft:cobblestone>]);
<recipetype:farmersdelight:cooking>.addRecipe("test_cooking_container", <item:minecraft:diamond>, [<item:minecraft:coal_block>, <item:minecraft:charcoal>], <item:minecraft:coal>);
<recipetype:farmersdelight:cooking>.addRecipe("test_cooking_experience_and_time", <item:minecraft:obsidian>, [<item:minecraft:water_bucket>], <item:minecraft:lava_bucket>, 100, 2);
```
And the `farmersdelight:cutting` recipe manager has two:
```zs
// <recipetype:farmersdelight:cutting>.addRecipe(String name, IIngredient input, IItemStack[] results, String toolTypeName, @OptionalString String sound)

<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_tool_type", <item:minecraft:diamond>, [<item:minecraft:coal_block>, <item:minecraft:coal>], "pickaxe");
<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_tool_type_sound", <item:minecraft:coal_block>, [<item:minecraft:diamond>], "axe", "minecraft:item.axe.strip");

// <recipetype:farmersdelight:cutting>.addRecipe(String name, IIngredient input, IItemStack[] results, IIngredient tool, @OptionalString String sound)

<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_ingredient", <item:minecraft:dirt>, [<item:minecraft:diamond>], <item:minecraft:diamond_sword>);
<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_ingredient_sound", <item:minecraft:gravel>, [<item:minecraft:flint>], <item:minecraft:string>, "minecraft:block.gravel.break");
```

Note that the new dependency on CraftTweaker is for 7.0.0.48, the latest for 1.16.3. [CraftTweaker had otherwise breaking changes in 7.1.0](https://docs.blamejared.com/1.16/en/migrations/migration_7_1_0/), but this should work fine with it.

### CODE REVIEW

**Comment by eutro** [comment]
Two new methods on `farmersdelight:cutting` for removals:
```zenscript
// <recipetype:farmersdelight:cutting>.removeRecipe(IItemStack output);

<recipetype:farmersdelight:cutting>.removeRecipe(<item:minecraft:crimson_planks>);

// <recipetype:farmersdelight:cutting>.removeRecipe(IItemStack[] outputs);

<recipetype:farmersdelight:cutting>.removeRecipe([<item:farmersdelight:cooked_salmon_slice> * 2, <item:minecraft:bone_meal>]);
```

**Comment by vectorwing** [comment]
I just merged #143 on 1.16.3, and I remember talking to you over whether these changes would be breaking. Just letting you know, let me know if you need anything else. =)

**Comment by eutro** [comment]
The tool type string-using method has been removed and replaced with the `<toolingredient:{tooltype}>` bracket handler.

New examples:
```zs
// <recipetype:farmersdelight:cooking>.addRecipe(String name, IItemStack output, IIngredient[] inputs, @Optional IItemStack container, @OptionalFloat float experience, @OptionalInt(200) int cookTime);

<recipetype:farmersdelight:cooking>.addRecipe("test_cooking", <item:minecraft:diamond>, [<item:minecraft:cobblestone>]);
<recipetype:farmersdelight:cooking>.addRecipe("test_cooking_container", <item:minecraft:enchanted_golden_apple>, [<item:minecraft:gold_block>], <item:minecraft:apple>);
<recipetype:farmersdelight:cooking>.addRecipe("test_cooking_experience_and_time", <item:minecraft:obsidian>, [<item:minecraft:water_bucket>], <item:minecraft:lava_bucket>, 100, 2);

// <recipetype:farmersdelight:cutting>.addRecipe(String name, IIngredient input, IItemStack[] results, IIngredient tool, @OptionalString String sound);

<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_tool_type", <item:minecraft:diamond>, [<item:minecraft:coal_block>, <item:minecraft:coal>], <toolingredient:pickaxe>);
<recipetype:farmersdelight:cutting>.addRecipe("test_cutting_tool_type_sound", <item:minecraft:coal_block>, [<item:minecraft:diamond>], <toolingredient:axe>, "minecraft:item.axe.strip");

// <recipetype:farmersdelight:cutting>.removeRecipe(IItemStack output);

<recipetype:farmersdelight:cutting>.removeRecipe(<item:minecraft:crimson_planks>);

// <recipetype:farmersdelight:cutting>.removeRecipe(IItemStack[] outputs);

<recipetype:farmersdelight:cutting>.removeRecipe([<item:farmersdelight:cooked_salmon_slice> * 2, <item:minecraft:bone_meal>]);
```

A caster for `ToolType`s to `IIngredient` has also been added, which is currently noop, but should work once [CraftTweaker has `ToolType` support](https://github.com/CraftTweaker/CraftTweaker/pull/1237)

**Comment by vectorwing** [comment]
Finally got a chance to try this out... Everything is working perfectly on my local repo! Excellent work ^^
Should I merge it right away, or is anything pending?

**Review by vectorwing — APPROVED** [review]

**Pull request merged**
