### PR TITLE
Update translation

### PR DESCRIPTION
**Pull request by FEMT1915**
Update ja_jp.json

### CODE REVIEW

**Comment by vectorwing** [comment]
Thank you for the update! 👍

**Comment by vectorwing** [comment]
Ah, I noticed you updated the 1.16.3 branch; currently FD is only being updated for 1.16.5.
Can you reopen the PR onto the other branch? Sorry for the confusion. ^^

**Comment by FEMT1915** [comment]
https://github.com/vectorwing/FarmersDelight/pull/290
Is this okay?

**Comment by vectorwing** [comment]
Indeed! Thanks for changing it =)

**Pull request closed without merging**
