### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by FrannDzs**

### CODE REVIEW

**Comment by vectorwing** [comment]
Hey there! Thank you for the update!

Looking over, I noticed a few words were swapped around for others, mostly meaning the same thing (going by Google Translate). I assume it's a dialect correction, in this case, which I know varies between Spanish-speaking countries. Would these be more accurate for the Spain dialect? Alternatively, does `es_` have multiple lang codes, like Portuguese has?

Sorry for asking, I just wanna understand this stuff better. ^^

**Comment by FrannDzs** [comment]
> Hey there! Thank you for the update!
> 
> Looking over, I noticed a few words were swapped around for others, mostly meaning the same thing (going by Google Translate). I assume it's a dialect correction, in this case, which I know varies between Spanish-speaking countries. Would these be more accurate for the Spain dialect? Alternatively, does `es_` have multiple lang codes, like Portuguese has?
> 
> Sorry for asking, I just wanna understand this stuff better. ^^

Hello, you're welcome. I am the same person who had translated that before, only now I corrected it dialectally to make it much more neutral and understandable for everyone. I have searched for information about some things and found definitions to be more accurate according to the context, so now the translation is better than the previous one. If you have a doubt please mark it in the specific line :)

Cheers!

**Comment by FrannDzs** [comment]
@vectorwing Hi, I plan to add templates for language variations, but I will not correct for each one, it will be used as a "base" for the translators of each country to modify. A little bit of Spanish is better than nothing, whenever you want to merge the PR. Greetings

**Comment by vectorwing** [comment]
Hey there! Sorry for the delay on replying, real life took over most of my free time.

Seems good! I'll do a final pass and merge it to current 1.16.5 later. I'm thinking of grouping these translations into a 0.4.4 update, since 0.5 will likely involve a *ton* of new langs.

**Comment by FrannDzs** [comment]
> Hey there! Sorry for the delay on replying, real life took over most of my free time.
> 
> Seems good! I'll do a final pass and merge it to current 1.16.5 later. I'm thinking of grouping these translations into a 0.4.4 update, since 0.5 will likely involve a _ton_ of new langs.

Hi, no problem, I know there is a life behind that screen :).
I will close this PR and open a new one with the new templates and some more fixes from the 1.16.5 branch. Greetings!

**Pull request closed without merging**
