### PR TITLE
added tag compat for create crafts and additions

### PR DESCRIPTION
**Pull request by moltenwolfcub**
Implemented the tags requested in issue #712.

### CODE REVIEW

**Comment by vectorwing** [comment]
Heyo, @moltenwolfcub, thanks for the PR! ^^

After checking the add-on, I noticed many of those items are already accounted for in different tags. Only 6 of them would require direct tagging, as seen below:

```
plants:
"farmersdelight:sandy_shrub"
"farmersdelight:brown_mushroom_colony",
"farmersdelight:red_mushroom_colony",

plant_foods:
"farmersdelight:pumpkin_slice"
"farmersdelight:rotten_tomato"
"farmersdelight:rice_panicle"
```

Also, I have recently added compatibility tags to data generation. Could you create these tags through there, so they can be generated together with `runData`? I can do this locally instead, if you prefer. 👍

Here's the file:
https://github.com/vectorwing/FarmersDelight/blob/1.18.2/src/main/java/vectorwing/farmersdelight/common/tag/CompatibilityTags.java

**Comment by moltenwolfcub** [comment]
I'll have a look at it.

**Comment by moltenwolfcub** [comment]
I think that should be updated to use datagen and those updated lists of items to be used in the tags.

**Comment by vectorwing** [comment]
Perfect! Thank you for the update; should be out on 1.2.2 soon. 👍

**Pull request merged**
