### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by gousisme**

### CODE REVIEW

**Comment by vectorwing** [comment]
Oh hey, you PR'd to the dev branch! Pretty cool.
Thanks for the new lang!

**Comment by gousisme** [comment]
I don't see vi_vn in the 1.19 version, should I create another merge request for that version as well? I'm new to this :d

**Comment by vectorwing** [comment]
The 1.19 branch was just created, and it's still undergoing error cleanup. Since it was started from the `1.18.2` branch, it won't have content from `dev-1.18/1.2` yet.

You can make a new PR to it if you want to! But 1.19 will have a few exclusive blocks/items later down, if you'd like to wait instead.

**Comment by gousisme** [comment]
alright I'll wait until the 1.19 version is out.

**Pull request merged**
