### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by NumberSir**

### CODE REVIEW

**Comment by vectorwing** [comment]
Thanks for the update! 👍

**Comment by Boshigiri** [comment]
Perhaps the translation of cabinet should be unified, rather than having a mix of the both 厨柜 and 橱柜

**Comment by Boshigiri** [comment]
Recommend to use 橱柜

**Comment by NumberSir** [comment]
> Perhaps the translation of cabinet should be unified, rather than having a mix of the both 厨柜 and 橱柜

你重新提一个 pr 就行，这个已经合并了。

如果可以的话给 [refabricated](https://github.com/MehVahdJukaar/FarmersDelightRefabricated/blob/fabric/1.21/src/main/resources/assets/farmersdelight/lang/zh_cn.json) 也提一个。

**Pull request merged**
