### PR TITLE
CHS Translation

### PR DESCRIPTION
**Pull request by WuzgXY-GitHub**
Please backport it to the other branches ..(:зゝ∠)..

### CODE REVIEW

**Comment by vectorwing** [comment]
Nicely done!
I noticed you left some context comments on the file for other translators. From the little I could Google Translate, they seem to make sense, at least. 😆

**Comment by WuzgXY-GitHub** [comment]
Yes, I wrote them to let reviewers, if there are, know where those names were from ^ ^

**Comment by EnterFor** [comment]
@WuzgXY-GitHub 好像加了几句字符串，大佬补下呗~ღ( ´･ᴗ･` )比心

**Comment by WuzgXY-GitHub** [comment]
> 
> 
> @WuzgXY-GitHub 好像加了几句字符串，大佬补下呗~ღ( ´･ᴗ･` )比心
> @WuzgXY-GitHub There are new untranslated strings, please add them to the CHS file

我已经放到新 PR 里了
I've opened a new pull request

**Pull request merged**
