### PR TITLE
Added ToolType ingredient serializer for cutting recipes

### PR DESCRIPTION
**Pull request by ochotonida**
I was browsing through your code a bit when I noticed that the cutting board recipe could probably be cleaned up a bit, since it applies a special case check for tool types. I then learned that it is apparently possible to add custom ingredient serializers, which removes the need for this special case behavior entirely. 

This PR removes the special case behavior for tool types in CuttingBoardRecipe and fixes issue #142 by adding a tool type ingredient & serializer. It should be noted that data packs which define cutting board recipes with a tool type will no longer work properly, as the `type` key in the `tool` ingredient is no longer used to define tool types (see #142).

### CODE REVIEW

**Comment by vectorwing** [comment]
Ooh, nicely done! I did notice it using "type" (which I personally liked for readability's sake), but it does block the ability to use custom ingredients or NBT.

And yes, presumably this will now be a breaking change for pack makers, which would entail a 0.4.0 version. I'll get back to you later once I see what's going into the next dot release. 👍

**Comment by ConductiveFoam** [comment]
First off, thanks! This is imo a great feature. I noticed one thing, however: Tools with dynamic types, like ImmersiveEngineering's Drill or Buzzsaw, don't work anymore with your Ingredient. There's a simple fix though, override the Ingredient's test:
```
@Override
public boolean test(ItemStack stack) {
    return stack.getToolTypes().contains(this.toolType) || super.test(stack);
}
```

**Comment by ochotonida** [comment]
I didn't notice tool types can be dynamic when I implemented this, good catch!

**Review by eutro — APPROVED** [review]
Everything looks good here to me.

**Comment by vectorwing** [comment]
Alright, everything seems good here too! Next version will be a 0.4 update, focusing on these changes, and maybe some new things.

**Pull request merged**
